app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/inicio/urls.py
from django.urls import path
from . import views

app_name = 'inicio'
urlpatterns = [
    path('', views.proyectos_list, name='proyectos_list'),
    path('ver_detalles/<int:id>/', views.ver_detalles, name='ver_detalles'),
    path('academico/<int:categoria_id>/', views.academico, name='academico'),
    path('colaboraciones/<int:categoria_id>/', views.colaboraciones, name='colaboraciones'),
    path('profesionales/<int:categoria_id>/', views.profesionales, name='profesionales'),
    path('experiencia-laboral/<int:categoria_id>/', views.exp_laboral, name='exp_laboral'),
    path('publicaciones/<int:categoria_id>/', views.publicaciones, name='publicaciones'),
    path('fotos/', views.fotografia, name='fotos'),
    ]

app/inicio/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField('Nombre de categoria', max_length=50, blank=True, null=True)

    def __str__(self):
        return self.nombre


class Proyecto(models.Model):
    nombre = models.CharField('Nombre del proyecto', max_length=100, blank=True, null=True)
    img_principal = models.ImageField(upload_to='principales/%Y/%m/%d', null=True, blank=True)
    ubicacion = models.CharField('Ubicacion', max_length=100, blank=True, null=True)
    anio = models.IntegerField('A#o', blank=True, null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    equipo = models.CharField('Equipo de proyecto',max_length=300, blank=True, null=True)
    descripcion = models.TextField('Memoria',blank=True, null=True)
    estado = models.BooleanField(default=True)
    orden = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name='Proyecto'
        verbose_name_plural='Proyectos'
        ordering = ['orden']

    def __str__(self):
        return self.nombre


class Imagen(models.Model):
    proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE,blank=True, null=True )
    img = models.ImageField(upload_to='imagenes/%Y/%m/%d', null=True)
    resumen = models.CharField('Explicacion',max_length=500, blank=True, null=True)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.proyecto.nombre

    class Meta:
        verbose_name='Imagen'
        verbose_name_plural='Imagenes'
        ordering=['id']

        
class Fofografia(models.Model):
    foto = models.ImageField(upload_to='fotos')
    estado = models.BooleanField(default=True)

    class Meta:
        verbose_name='Foto'
        verbose_name_plural='Fotos'
        ordering=['-id']


    



    

app/inicio/views.py
from django.shortcuts import render
from .models import Proyecto,Imagen,Fofografia


def proyectos_list(request):
    proyectos = Proyecto.objects.filter(estado=True)
    return render(request, 'inicio/proyectos.html', {'proyectos': proyectos})

def ver_detalles(request, id):
    detalles = Imagen.objects.filter(proyecto=id)
    contexto = {
        'detalles':detalles,
    }
    return render(request, 'inicio/galeria.html', contexto)

def academico(request, categoria_id):
    academicos = Proyecto.objects.filter(categoria_id=2)
    contexto = {'academicos':academicos}
    return render(request, 'inicio/academico.html', contexto)

def colaboraciones(request, categoria_id):
    colaboraciones = Proyecto.objects.filter(categoria_id=1)
    return render(request, 'inicio/colaboraciones.html', {'colaboraciones':colaboraciones})

def profesionales(request, categoria_id):
    profesionales = Proyecto.objects.filter(categoria_id=3)
    return render(request, 'inicio/profesionales.html', {'profesionales':profesionales})

def exp_laboral(request, categoria_id):
    laborales = Proyecto.objects.filter(categoria_id=4)
    return render(request, 'inicio/exp_laboral.html', {'laborales':laborales})

def publicaciones(request, categoria_id):
    publicaciones = Proyecto.objects.filter(categoria_id=5)
    return render(request, 'inicio/publicaciones.html', {'publicaciones':publicaciones})

def fotografia(request):
    fotos = Fofografia.objects.filter(estado=True)
    return render(request, 'inicio/fotografia.html', {'fotos':fotos})

app/inicio/templates/inicio/academico.html
{% extends "inicio/index.html" %}

{% block nav %}
<nav class="navbar navbar-expand-md fixed-top mb-auto  navbar-light navbar-toggleable-md menu-fixed">
  <!-- Brand -->
 <label><a class="navbar-brand nombre" href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a></label> 
  <!-- Button collapse -->
<button class="navbar-toggler" data-toggle="collapse" data-target="#contenido-nav" aria-controls="contenido-nav" aria-expanded="false">
<span class="navbar-toggler-icon"></span>
</button>
  <!-- Nav content -->
  <div class="collapse navbar-collapse" id="contenido-nav">
    <div class="navbar-nav text-center ml-auto desplegable">
          <a class="nav-item nav-link menu active" aria-current="page" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral </a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:fotos' %}">Fotografias</a>
      </div>
  </div>
</nav>

<!-- <nav class="menu">
  <label class="logo"><a href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a> </label>
  <ul class="menu_items">
      <li><a class="active" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a></li>
      <li><a href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a></li>
      <li><a href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a></li>
      <li><a href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a></li>
      <li><a href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a></li>
      <li><a href="{% url 'inicio:fotos' %}">Fotografias</a></li>
  </ul>
  <span class="btn_menu">
      <i class="fa fa-bars"></i>
  </span>
</nav> -->
    <!-- <nav class="menu-fixed">
      <div class="d-flex flex-column flex-md-row align-items-center bg-white">
      <h5 class="my-0 mr-md-auto inicio"><a href="{% url 'inicio:proyectos_list' %} "><span class='name'>GABRIEL BORELLA -</span> <spam class="arq">ARQUITECTO</spam></h5></a> 

      <a class="nav-item active nav-link p-2 menu" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:fotos' %}">Fotografia</a>
    </div>
    <br>
  </nav> 
  <br><br><br><br> -->
  {% endblock nav %}
{% block content %}
 <div class="container-fluid">
  {% for academico in academicos %}
  <section class="personas">
    <div class="contenedor">
      <article class="persona__columna">
        <a href="{% url 'inicio:ver_detalles' academico.id %}"><img src="{{academico.img_principal.url}}"></a>
      </article>
    </div>
  </section>
  {% endfor %}
</div>
{% endblock content %}

<div class="col-4 imag efecto">
  <a href="{% url 'inicio:ver_detalles' academico.id %}"><img src="{{academico.img_principal.url}}" 
  class="principal" 
  style="height: 220px;
  width: 350px;">
   </a>
</div>

app/inicio/templates/inicio/colaboraciones.html
{% extends "inicio/index.html" %}

{% block nav %}
<nav class="navbar navbar-expand-md fixed-top mb-auto  navbar-light navbar-toggleable-md menu-fixed">
  <!-- Brand -->
 <label><a class="navbar-brand nombre" href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a></label> 
  <!-- Button collapse -->
<button class="navbar-toggler" data-toggle="collapse" data-target="#contenido-nav" aria-controls="contenido-nav" aria-expanded="false">
<span class="navbar-toggler-icon"></span>
</button>
  <!-- Nav content -->
  <div class="collapse navbar-collapse" id="contenido-nav">
    <div class="navbar-nav text-center ml-auto desplegable">
          <a class="nav-item nav-link menu" aria-current="page" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
          <a class="nav-item nav-link menu active" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral </a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:fotos' %}">Fotografias</a>
      </div>
  </div>
</nav>
<!-- <nav class="menu">
  <label class="logo"><a href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a> </label>
  <ul class="menu_items">
      <li><a href="{% url 'inicio:academico' categoria_id=2 %}" hreh="#">Academicos</a></li>
      <li><a class="active" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a></li>
      <li><a href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a></li>
      <li><a href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a></li>
      <li><a href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a></li>
      <li><a href="{% url 'inicio:fotos' %}">Fotografias</a></li>
  </ul>
  <span class="btn_menu">
      <i class="fa fa-bars"></i>
  </span>
</nav> -->
    <!-- <nav class="menu-fixed">
      <div class="d-flex flex-column flex-md-row align-items-center bg-white">
      <h5 class="my-0 mr-md-auto inicio"><a href="{% url 'inicio:proyectos_list' %} "><span class='name'>GABRIEL BORELLA -</span> <spam class="arq">ARQUITECTO</spam></h5></a> 

      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
      <a class="nav-item active nav-link p-2 menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:fotos' %}">Fotografia</a>
    </div>
    <br>
  </nav>  -->
  {% endblock nav %}
  
{% block content %}
<div class="container-md">
  {% for colaboracion in colaboraciones %}
  <section class="personas">

    <div class="contenedor">
      
      <article class="persona__columna">
        

        <a href="{% url 'inicio:ver_detalles' colaboracion.id %}"><img src="{{colaboracion.img_principal.url}}"></a>

        
      </article>
      
    </div>

  </section>
  {% endfor %}
</div>
{% endblock content %}

<div class="col-4 imag efecto">
  <a href="{% url 'inicio:ver_detalles' colaboracion.id %}"><img src="{{colaboracion.img_principal.url}}" 
  class="principal" 
  style="height: 220px;
  width: 350px;">
   </a>
</div>

app/inicio/templates/inicio/exp_laboral.html
{% extends "inicio/index.html" %}

{% block nav %}
<nav class="navbar navbar-expand-md fixed-top mb-auto  navbar-light navbar-toggleable-md menu-fixed">
  <!-- Brand -->
 <label><a class="navbar-brand nombre" href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a></label> 
  <!-- Button collapse -->
<button class="navbar-toggler" data-toggle="collapse" data-target="#contenido-nav" aria-controls="contenido-nav" aria-expanded="false">
<span class="navbar-toggler-icon"></span>
</button>
  <!-- Nav content -->
  <div class="collapse navbar-collapse" id="contenido-nav">
    <div class="navbar-nav text-center ml-auto desplegable">
          <a class="nav-item nav-link menu" aria-current="page" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
          <a class="nav-item nav-link menu " href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
          <a class="nav-item nav-link menu active" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral </a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:fotos' %}">Fotografias</a>
      </div>
  </div>
</nav>
<!-- <nav class="menu">
  <label class="logo"><a href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a> </label>
  <ul class="menu_items">
      <li><a href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a></li>
      <li><a href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a></li>
      <li><a href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a></li>
      <li><a  class="active" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a></li>
      <li><a href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a></li>
      <li><a href="{% url 'inicio:fotos' %}">Fotografias</a></li>
  </ul>
  <span class="btn_menu">
      <i class="fa fa-bars"></i>
  </span>
</nav> -->
    <!-- <nav class="menu-fixed">
      <div class="d-flex flex-column flex-md-row align-items-center bg-white">
      <h5 class="my-0 mr-md-auto inicio"><a href="{% url 'inicio:proyectos_list' %} "><span class='name'>GABRIEL BORELLA -</span> <spam class="arq">ARQUITECTO</spam></h5></a> 

      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
      <a class="nav-item active nav-link p-2 menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:fotos' %}">Fotografia</a>
    </div>
    <br>
  </nav>  -->
  {% endblock nav %}

{% block content %}
<div class="container-fluid">
  {% for exp_laboral in laborales %}
  <section class="personas">

    <div class="contenedor">
      
      <article class="persona__columna">
        

        <a href="{% url 'inicio:ver_detalles' exp_laboral.id %}"><img src="{{exp_laboral.img_principal.url}}"></a>

        
      </article>
      
    </div>

  </section>
  {% endfor %}
</div>
{% endblock content %}

<div class="col-4 imag efecto">
  <a href="#"><img src="{{exp_laboral.img_principal.url}}" class="principal" style="height: 220px;
  width: 350px;"></a>
</div>

app/inicio/templates/inicio/profesionales.html
{% extends "inicio/index.html" %}

{% block nav %}
<nav class="navbar navbar-expand-md fixed-top mb-auto  navbar-light navbar-toggleable-md menu-fixed">
  <!-- Brand -->
 <label><a class="navbar-brand nombre" href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a></label> 
  <!-- Button collapse -->
<button class="navbar-toggler" data-toggle="collapse" data-target="#contenido-nav" aria-controls="contenido-nav" aria-expanded="false">
<span class="navbar-toggler-icon"></span>
</button>
  <!-- Nav content -->
  <div class="collapse navbar-collapse" id="contenido-nav">
    <div class="navbar-nav text-center ml-auto desplegable">
          <a class="nav-item nav-link menu" aria-current="page" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
          <a class="nav-item nav-link menu active" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral </a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:fotos' %}">Fotografias</a>
      </div>
  </div>
</nav>
<!-- <nav class="menu">
  <label class="logo"><a href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a> </label>
  <ul class="menu_items">
      <li><a href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a></li>
      <li><a href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a></li>
      <li><a class="active" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a></li>
      <li><a href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a></li>
      <li><a href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a></li>
      <li><a href="{% url 'inicio:fotos' %}">Fotografias</a></li>
  </ul>
  <span class="btn_menu">
      <i class="fa fa-bars"></i>
  </span>
</nav> -->
    <!-- <nav class="menu-fixed">
      <div class="d-flex flex-column flex-md-row align-items-center bg-white">
      <h5 class="my-0 mr-md-auto inicio"><a href="{% url 'inicio:proyectos_list' %} "><span class='name'>GABRIEL BORELLA -</span> <spam class="arq">ARQUITECTO</spam></h5></a> 

      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
      <a class="nav-item active nav-link p-2 menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
      <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:fotos' %}">Fotografia</a>
    </div>
    <br>
  </nav>  -->
  {% endblock nav %}

{% block content %}
<div class="container-fluid">
  {% for profesional in profesionales %}
  <section class="personas">

    <div class="contenedor">
      
      <article class="persona__columna">
        

        <a href="{% url 'inicio:ver_detalles' profesional.id %}"><img src="{{profesional.img_principal.url}}"></a>

        
      </article>
      
    </div>

  </section>
  {% endfor %}
</div>


{% endblock content %}

<div class="col-4 imag efecto">
  <a href="{% url 'inicio:ver_detalles' profesional.id %}"><img src="{{profesional.img_principal.url}}" 
  class="principal" 
  style="height: 220px;
  width: 350px;">
   </a>
</div>

app/inicio/templates/inicio/proyectos.html
{% extends "inicio/index.html" %}
<div class="container-md">
{% block nav %}
<nav class="navbar navbar-expand-md fixed-top mb-auto  navbar-light navbar-toggleable-md menu-fixed">
  <!-- Brand -->
 <label><a class="navbar-brand nombre active" href="#">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a></label> 
  <!-- Button collapse -->
<button class="navbar-toggler" data-toggle="collapse" data-target="#contenido-nav" aria-controls="contenido-nav" aria-expanded="false">
<span class="navbar-toggler-icon"></span>
</button>
  <!-- Nav content -->
  <div class="collapse navbar-collapse" id="contenido-nav">
    <div class="navbar-nav text-center ml-auto desplegable">
          <a class="nav-item nav-link menu" aria-current="page" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral </a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
          <a class="nav-item nav-link menu" href="{% url 'inicio:fotos' %}">Fotografias</a>
      </div>
  </div>
</nav>
{% endblock nav %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 columnas">
  {% for proyecto in proyectos %}
<section class="personas">
    <div class="contenedor">

      <article class="persona__columna">
        <a href="{% url 'inicio:ver_detalles' proyecto.id %}"><img src="{{proyecto.img_principal.url}}"></a>
        <div class="capa">
          <p>{{proyecto.nombre}}</p>
        </div>
      </article>
      
    </div>
  </section>
  {% endfor %}
</div>
</div>
</div>
{% endblock content %}



<div class="col-4 imag efecto">
  <figure>

    <a href="{% url 'inicio:ver_detalles' proyecto.id %}"><img src="{{proyecto.img_principal.url}}"></a>

    <div class="capa">
      <p>{{proyecto.nombre}}</p>
    </div>

  </figure>
</div>   


<nav class="menu-fixed">
  <div class="d-flex flex-column flex-md-row align-items-center bg-white">
  <h5 class="my-0 mr-md-auto inicio"><a class="" href="{% url 'inicio:proyectos_list' %} "><span class='name'>GABRIEL BORELLA -</span> <spam class="arq">ARQUITECTO</spam></h5></a> 

  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a>
  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a>
  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a>
  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a>
  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a>
  <a class="nav-item nav-link p-2 menu" href="{% url 'inicio:fotos' %}">Fotografia</a>
</div>
<br>
</nav> 
<br><br><br><br>





<nav class="menu">
  <label class="logo"><a  class="active" href="{% url 'inicio:proyectos_list' %}">GABRIEL BORELLA - <span class="arq">ARQUITECTO</span></a> </label>
  <ul class="menu_items">
      <li><a href="{% url 'inicio:academico' categoria_id=2 %}">Academicos</a></li>
      <li><a href="{% url 'inicio:colaboraciones' categoria_id=1 %}">Colaboraciones</a></li>
      <li><a href="{% url 'inicio:profesionales' categoria_id=3 %}">Proyectos profesionales</a></li>
      <li><a href="{% url 'inicio:exp_laboral' categoria_id=4 %}">Experiencia laboral</a></li>
      <li><a href="{% url 'inicio:publicaciones' categoria_id=5 %}">Publicaciones</a></li>
      <li><a href="{% url 'inicio:fotos' %}">Fotografias</a></li>
  </ul>
  <span class="btn_menu">
      <i class="fa fa-bars"></i>
  </span>
</nav>